language: generic
sudo: required
serviecs:
  - docker

before_install:
  - docker build -t hushun/docker-react-stephen -f Dockerfile.dev .

script:
  - docker run -e CI=true hushun/docker-react-stephen npm run test